return {
	'kevinhwang91/nvim-bqf',
	ft = 'qf',
	opts = {
		preview = {
			auto_preview = false,
			-- winblend = 0, -- Set this to match your default transparency (0-100)
			win_height = 30,
			win_vheight = 30,
		},
		func_map = {
			drop = 'O',
			filter = 'zn',
			filterr = 'zN',
			fzffilter = 'zf',
			lastleave = '\'"',
			nextfile = '<C-n>',
			nexthist = '>',
			open = '<CR>',
			openc = 'o',
			prevfile = '<C-p>',
			prevhist = '<',
			pscrolldown = '<C-f>',
			pscrollorig = 'zo',
			pscrollup = '<C-b>',
			ptoggleauto = 'P',
			ptoggleitem = 'p',
			ptogglemode = 'zp',
			sclear = 'z<Tab>',
			split = '<C-x>',
			stogglebuf = "'<Tab>",
			stoggledown = '<Tab>',
			stoggleup = '<S-Tab>',
			stogglevm = '<Tab>',
			tab = 't',
			tabb = 'T',
			tabc = '<C-t>',
			tabdrop = '',
			vsplit = '<C-v>',
		},
	},
	config = function(_, opts)
		require('bqf').setup(opts)
	end,
}
